### PR TITLE
refactor: Move feature flags to webpack, and fix react error of no key on list

### LINKED ISSUE #11: Configure webpack to ensure dryruns are disabled in prod

### PR DESCRIPTION
**Pull request by angusy29**
https://github.com/angusy29/CantoTranslate/issues/11

### CODE REVIEW

File: src/configurations/featureFlagTypes.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// All these are global types, defined in webpack.dev.js and webpack.prod.js
+// https://stackoverflow.com/questions/44655095/global-variables-are-undefined-in-typescript-coming-from-webpack
+
+// declare statement required to silence typescript
+// as webpack defines global variables
+declare const mock_get_definition: boolean;
+const _mock_get_definition = mock_get_definition;
+export { _mock_get_definition as mock_get_definition };
```
Comment (tan-eddie) [inline src/configurations/featureFlagTypes.ts:8]: What do these two lines do? Was just the `declare const` above not enough?

**Review by tan-eddie — APPROVED** [review]
lgtm, just a question

File: src/configurations/featureFlagTypes.ts (hunk 1 above)
Comment (angusy29) [reply src/configurations/featureFlagTypes.ts:8]: You assume I actually know what I'm doing, apparently it returns `undefined` without the assignment and export, see Stackoverflow link above
